- hosts: 
  become: yes
  tasks:
  - name: install apache server
    yum:
      name: httpd
      state: present
  - name: deploy index.html on apache server
    copy:
      src: index.html
      dest: /var/www/html
  - name: start and enable
    service:
      name: httpd
      state: started
      enabled: yes